# fly.toml app configuration file generated for casa-nei-fiori on 2025-03-05T15:31:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'casa-nei-fiori'
primary_region = 'fra'

[build]
  builder = 'paketobuildpacks/builder:full'

[deploy]
  release_command = 'npm install'

[env]
  PORT = '3000'

[processes]
  app = 'node server.js'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
